### ISSUE TITLE
Reduce boilerplate with more defaults to attr.ib()

### ISSUE THREAD

**Issue by skewty** [MacHu-GWU/attrs_mate-project#1]
There is still a lot of boilerplate to get the following "mate" additions:
```python
    profile = attr.ib(
        converter=Profile.from_dict,
        validator=attr.validators.optional(
            attr.validators.instance_of(Profile)
        ),
        factory=Profile,
    )
```
### Have you considered going one step further with:

1. having a default converter?  (the default could be overridden using a new parameter to `attr.s` decorator.)  (The default could rely on the attrib.type field (or :typehint in Py3.6))
2. having a default validator?  (an additional new parameter to `attr.s` of `type_validate_all=False` when True it would automatically verify the type as in `attr.validators.instance_of(Profile)`)

**Comment by MacHu-GWU** [comment]
@skewty  could you write some fake code to show what is the expected API? I assume that you are expecting:

```python
@attr.s
class Profile(AttrsClass):
    """
    firstname, lastname, ssn are generic data type field.
    """
    firstname = attr.ib(default=None)
    lastname = attr.ib(default=None)
    ssn = attr.ib(default=None)


@attr.s
class Degree(AttrsClass):
    name = attr.ib(default=None)
    year = attr.ib(default=None)


@attr.s
class People(AttrsClass):
    """
    - ``profile`` is nested field.
    - ``degrees`` is collection type field.
    """
    id = attr.ib(default=None)
    profile = attr.ib(nested_class=Profile)
    degrees = attr.ib(nested_list_of_class=Degree)
```

Am I correct?

**Comment by MacHu-GWU** [comment]
@skewty sorry for the late reply. this is supported in the release 0.0.5 on late 2019
